### ISSUE TITLE
Help adding a 

### ISSUE THREAD

**Issue by chuckberrypi** [Gonzih/cljs-electron#23]
I'm really enjoying playing around with this template, but need some help, probably because I am still rather new to the cljs tooling ecosystem used here. 

I have an idea for a program I would like to use for work, but it requires somewhat intensive processing of a large number of pdfs. Based on [this article](https://medium.com/actualbudget/the-horror-of-blocking-electrons-main-process-351bf11a763c), I think I should have that happen in a separate process that the main process communicates with. 

So I added a "pdf_src" directory, put in a pdf.core namespace, and added the following to the :builds defined in project.clj :
`{:source-paths ["pdf_src"]
     :id "pdf-dev"
     :compiler {:output-to "resources/pdf.js"
                :output-dir "resources/public/js/pdf-dev"
                :optimizations :simple
                :pretty-print true
                :cache-analysis true}}`

I added `pdf:      env LEIN_FAST_TRAMPOLINE=y lein trampoline cljsbuild auto pdf-dev` to the procfile. 

My goal is to put the code for the background tasks in the pdf.js file and then fork a node process to run that file from main. 

But running `lein cooper` gives me a whole stack of compilation errors. 

`Compiling ["resources/pdf.js"] failed.
clojure.lang.ExceptionInfo: null #:clojure.error{:phase :compilation}
        at cljs.util$compilation_error.invokeStatic(util.cljc:23)
        at cljs.util$compilation_error.invoke(util.cljc:22)
        at cljs.closure$write_js_QMARK_.invokeStatic(closure.clj:2058)
        at cljs.closure$write_js_QMARK_.invoke(closure.clj:2047)
        at cljs.closure$source_on_disk.invokeStatic(closure.clj:2064)
        at cljs.closure$source_on_disk.invoke(closure.clj:2060)
        at cljs.closure$build$fn__6208.invoke(closure.clj:3020)
        at clojure.core$map$fn__5851.invoke(core.clj:2755)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:709)
        at clojure.core$next__5371.invokeStatic(core.clj:64)
        at clojure.core$dorun.invokeStatic(core.clj:3142)
        at clojure.core$doall.invokeStatic(core.clj:3148)
        at clojure.core$doall.invoke(core.clj:3148)
        at cljs.closure$build.invokeStatic(closure.clj:3020)
        at cljs.closure$build.invoke(closure.clj:2919)
        at cljs.build.api$build.invokeStatic(api.clj:208)
        at cljs.build.api$build.invoke(api.clj:189)
        at cljs.build.api$build.invokeStatic(api.clj:195)
        at cljs.build.api$build.invoke(api.clj:189)
        at cljsbuild.compiler$compile_cljs$fn__709.invoke(compiler.clj:61)
        at cljsbuild.compiler$compile_cljs.invokeStatic(compiler.clj:60)
        at cljsbuild.compiler$compile_cljs.invoke(compiler.clj:48)
        at cljsbuild.compiler$run_compiler.invokeStatic(compiler.clj:168)
        at cljsbuild.compiler$run_compiler.invoke(compiler.clj:129)
        at user$eval838$iter__886__890$fn__891$fn__917.invoke(form-init7740181582868617844.clj:1)
        at user$eval838$iter__886__890$fn__891.invoke(form-init7740181582868617844.clj:1)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:531)
        at clojure.core$seq__5387.invokeStatic(core.clj:137)
        at clojure.core$dorun.invokeStatic(core.clj:3133)
        at clojure.core$doall.invokeStatic(core.clj:3148)
        at clojure.core$doall.invoke(core.clj:3148)
        at user$eval838.invokeStatic(form-init7740181582868617844.clj:1)
        at user$eval838.invoke(form-init7740181582868617844.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7176)
        at clojure.lang.Compiler.eval(Compiler.java:7166)
        at clojure.lang.Compiler.load(Compiler.java:7635)
        at clojure.lang.Compiler.loadFile(Compiler.java:7573)
        at clojure.main$load_script.invokeStatic(main.clj:452)
        at clojure.main$init_opt.invokeStatic(main.clj:454)
        at clojure.main$init_opt.invoke(main.clj:454)
        at clojure.main$initialize.invokeStatic(main.clj:485)
        at clojure.main$null_opt.invokeStatic(main.clj:519)
        at clojure.main$null_opt.invoke(main.clj:516)
        at clojure.main$main.invokeStatic(main.clj:598)
        at clojure.main$main.doInvoke(main.clj:561)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: Could not write JavaScript nil
        ... 51 more
Subprocess failed
`

What am I missing? Any help would be much appreciated.

**Comment by Gonzih** [comment]
Was this repo working without any changes on your machine?

**Comment by chuckberrypi** [comment]
Yes, it was working great.

**Comment by Gonzih** [comment]
Is your code maybe somewhere on github so I can take a look at it?

**Comment by chuckberrypi** [comment]
Just uploaded it. Thanks for looking! https://github.com/chuckberrypi/pdf

**Comment by Gonzih** [comment]
Checked out your repo, it compiles and works for me fine!

**Comment by chuckberrypi** [comment]
Ha, OK. Thanks for checking, anyway! I guess there’s something on my machine that’s giving me problems then.

**Comment by Gonzih** [comment]
I will close the issue for now, feel free to re-open if you need help in the future.
